### DISCUSSION TITLE
regexMatches is not working inside predicateMatchSpec

### DISCUSSION THREAD

**Discussion by armanbaghajyan** [aquasecurity/tfsec#1609] [Help and suppports] [answered]
Hi, First of all, I want to mention that tfsec is awsome. I researched a lot for a tool that I can use for scanning my terraform code and found that tfsec is the best for now.
Thank you for that.

I am trying to write custom rule to check resources for required tags and cant check values with regexp matches inside predicateMatchSpec.

tfsec version: 1.11.0

here is working example

```    
matchSpec:
      name: key_name
      action: regexMatches
      value: "^NAME-\\d+$"
```
      
but here it is not working
```
    matchSpec:
      name: tags
      action: isPresent
      subMatch:
        action: and
        predicateMatchSpec:
          - name: NAME
            action: regexMatches
            value: "^NAME-\\d+$"
          - name: NAME2
            action: regexMatches
            value: "^NAME-\\d+$"
```

**Comment by armanbaghajyan** [comment, marked as answer]
Thanks, @owenrumney for helping me.
Here is the configuration that worked for me

```
 matchSpec:
      action: and
      predicateMatchSpec:
      - action: contains
        name: tags
        value: Owner
      - action: contains
        name: tags
        value:
          Squad:
            action: regexMatches
            value: "^SQUAD-\\d+$"
```
If you want to specific Owners you can do something like
```
    matchSpec:
      action: and
      predicateMatchSpec:
      - action: contains
        name: tags
        value: 
          Owner:
            action: isAny
            value:
            - Engineering
            - Ops
            - Test
      - action: contains
        name: tags
        value:
          Squad:
            action: regexMatches
            value: "^SQUAD-\\d+$"
```
