### DISCUSSION TITLE
Example for those who want to use it in gitlab-ci

### DISCUSSION THREAD

**Discussion by cmachadox** [aquasecurity/tfsec#1712] [Developement]
I'm currently using it in some projects, it's been very useful

here's an example of how it shows me in gitlab:

![image](https://user-images.githubusercontent.com/30154971/167025356-f9d8dedf-6f04-43da-8a54-53a90ec6e7e3.png)

```yml
stages:
  - tfsec

validate:
  stage: tfsec
  tags:
    - pages
  image:
    name: tfsec/tfsec-ci
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    -  tfsec -f junit --out tfsec.test.xml
  artifacts:
    reports:
      junit: "tfsec.test.xml"
    paths:
      - tfsec.test.xml
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
```
