### DISCUSSION TITLE
Not a PR, nothing to comment on, exiting...

### DISCUSSION THREAD

**Discussion by samarth3112** [aquasecurity/tfsec#1825] [Help and suppports]
I m getting below error while using in reusbale workflow.

starting the github commenter...
Not a PR, nothing to comment on, exiting...

Can you suggest a fix

**Comment by adilburaksen** [comment]
The `tfsec-pr-commenter-action` only does something when the workflow is triggered by a `pull_request` (or `pull_request_target`) event. Any other trigger — `push`, `workflow_dispatch`, scheduled, etc. — causes it to print "Not a PR, nothing to comment on, exiting..." and exit cleanly.

Check your reusable workflow caller. The event that triggered the parent workflow must be a pull request event for the commenter to have a PR to annotate.

```yaml
# caller workflow — must be triggered by pull_request
on:
  pull_request:
    branches: [main]

jobs:
  security:
    uses: your-org/reusable-workflows/.github/workflows/tfsec.yml@main
```

If you want the tfsec scan to run on both pushes and PRs but only comment on PRs, add a condition on the commenter step:

```yaml
- name: tfsec PR commenter
  uses: aquasecurity/tfsec-pr-commenter-action@v1
  if: github.event_name == 'pull_request'
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
```

The scan step itself can run unconditionally; the commenter just won't post anything when there's no PR to attach to.
