### ISSUE TITLE
Custom check definition help

### ISSUE THREAD

**Issue by MilindPurswani** [aquasecurity/tfsec#1000]
Hi team,

I am trying to develop a custom check to evaluate this condition:

( 0.0.0.0/0 **or** Type = Public ) **and** Port 22

If this condition is satisfied, it should raise an error. Basically, I have expanded the above statement to:

(0.0.0.0/0 **and** Port 22) **or** ( Type = Public **and** Port 22) 

Here is the custom check file created for this check:

```json
{
  "checks": 
  [
    {
      "code": "CUS001",
      "description": "Custom check to ensure no instance has SSH open to internet with public tag",
      "impact": "If an instance has SSH accessible to internet with public tag, then that instance is not abiding by the AWS security standards",
      "resolution": "Remove the SSH access for public instances",
      "requiredTypes": 
      [
        "resource"
      ],
      "requiredLabels": 
      [
        "aws_security_group"
      ],
      "severity": "ERROR",
      "matchSpec": 
      {
        "action": "or",
        "predicateMatchSpec": 
        [
          {
            "name": "ingress",
            "action": "isPresent",
            "subMatch": 
            {
              "action": "and",
              "predicateMatchSpec": 
              [
                {
                  "name": "cidr_blocks",
                  "action": "contains",
                  "value": "0.0.0.0/0"
                },
                {
                  "name": "from_port",
                  "action": "contains",
                  "value": "22"
                }
              ]
            }
          },
          {
            "action":"and",
            "predicateMatchSpec": 
            [
              {
                "name": "Type",
                "action": "equals",
                "value": "Public"
              },
              {
                "name":"ingress",
                "action":"isPresent",
                "subMatch": 
                {
                  "name":"from_port",
                  "action":"contains",
                  "value": "22"
                }
              }
            ]
          }
        ]
      },
      "errorMessage": "[Error] Port 22 open for a public instance",
      "relatedLinks": [
        "http://internal.acmecorp.com/standards/aws/tagging.html"
      ]
    }
  ]   
}
```

Unfortunately, it doesn't trigger it for this file: 

```hcl
resource "aws_security_group" "test" {
  name = "allow-all-sg"
  description = "Allowing everyone to connect to this public instance"
  vpc_id = "${aws_vpc.my_vpc.id}"
  ingress {
    cidr_blocks = ["0.0.0.0/0"]
    from_port = "22"
    to_port = "22"
    protocol = "tcp"
  }
  tags = {
    Type = "Public"
  }

  egress {
    from_port = 0
    to_port = 0
    protocol = "-1"
    cidr_blocks = ["0.0.0.0/0"]
 }
}
```

Is there something that I am missing here? 

Thanks,

**Comment by MilindPurswani** [comment]
Looks like I created the 1000th Issue after tfsec moved to Aquasecurity. I hope you guys are planning a small party once this issue is resolved 😛

**Comment by owenrumney** [comment]
Hey @MilindPurswani - sorry for the delay in coming back to this.

You've highlighted the need for a couple of changes in the what that custom actions work, most specifically that we need the concept of a `preCondition` which is required before the check even runs.

In your example there were a few additional changes - 

```json
{
  "checks": [
    {
      "code": "CUS001",
      "description": "Custom check to ensure no instance has SSH open to internet with public tag",
      "impact": "If an instance has SSH accessible to internet with public tag, then that instance is not abiding by the AWS security standards",
      "resolution": "Remove the SSH access for public instances",
      "requiredTypes": [
        "resource"
      ],
      "requiredLabels": [
        "aws_security_group"
      ],
      "severity": "ERROR",
      "matchSpec": {
        "action": "or",
        "predicateMatchSpec": [
          {
            "name": "ingress",
            "action": "isPresent",
            "subMatch": {
              "action": "and",
              "predicateMatchSpec": [
                {
                  "name": "cidr_blocks",
                  "action": "notContains",
                  "value": "0.0.0.0/0"
                },
                {
                  "name": "from_port",
                  "action": "notEqual",
                  "value": "22"
                }
              ]
            }
          },
          {
            "preConditions": [
              {
                "name": "ingress",
                "action": "isPresent"
              },
              {
                "name": "tags",
                "action": "contains",
                "value": {
                  "Type": "Public"
                }
              }
            ],
            "name": "from_port",
            "action": "notEqual",
            "value": "22"
          }
        ]
      },
      "errorMessage": "[Error] Port 22 open for a public instance",
      "relatedLinks": [
        "http://internal.acmecorp.com/standards/aws/tagging.html"
      ]
    }
  ]
}
```

Notice that the check now looks for `notContains` the open CIDR and `notEqual` to 22. It also checks that `tags` `contains` `Type:Public` as a precondition.

**Comment by owenrumney** [comment]
You also have the option of using yaml which might be more concise :shrug: 

```yaml
---
checks:
- code: CUS001
  description: Custom check to ensure no instance has SSH open to internet with public
    tag
  impact: If an instance has SSH accessible to internet with public tag, then that
    instance is not abiding by the AWS security standards
  resolution: Remove the SSH access for public instances
  requiredTypes:
  - resource
  requiredLabels:
  - aws_security_group
  severity: ERROR
  matchSpec:
    action: or
    predicateMatchSpec:
    - name: ingress
      action: isPresent
      subMatch:
        action: and
        predicateMatchSpec:
        - name: cidr_blocks
          action: notContains
          value: 0.0.0.0/0
        - name: from_port
          action: notEqual
          value: '22'
    - preConditions:
      - name: ingress
        action: isPresent
      - name: tags
        action: contains
        value:
          Type: Public
      name: from_port
      action: notEqual
      value: '22'
  errorMessage: "[Error] Port 22 open for a public instance"
  relatedLinks:
  - http://internal.acmecorp.com/standards/aws/tagging.html

```
