### ISSUE TITLE
merge function breaks custom tag check

### ISSUE THREAD

**Issue by heathsnow** [aquasecurity/tfsec#1054]
**Describe the bug**
I have a custom check that ensures a specific tag is assigned to resources that accept tags.  However, in the case that the `merge` function is used to set tag values on a resource the check fails when it shouldn't.

<details>
  <summary>custom_tfchecks.yaml</summary>
    <p>

```yaml
  ---
  checks:
  - code: CUS001
    description: Custom check to ensure the repo tag is applied to all AWS resources
    impact: By not having a `repo` tag we can't keep track of IaC configuration location
    resolution: Add the `repo` tag
    requiredTypes:
    - resource
    requiredLabels:
    - aws_*
    severity: ERROR
    matchSpec:
      name: tags
      action: contains
      value: repo
      ignoreUndefined: true
    errorMessage: The required `repo` tag was missing
    relatedLinks:
    - https://d1.awsstatic.com/whitepapers/aws-tagging-best-practices.pdf
```

  </p>
</details>

<details>
  <summary>Resource tag example</summary>
    <p>

```hcl
tags = merge(
  var.tags,
  { "Name" = "foo" }
)
```

    </p>
</details>

<details>
  <summary>variables.tf</summary>
    <p>

```hcl
variable "tags" {
  type = map(any)
  default = {
    repo = "https://github.com/foo"
  }
}
```

    </p>
</details>

**To Reproduce**
1. Using the configuration outlined above tfsec throws an `ERROR` even though the resource tag contains a tag key named `repo`.  This error happens when the `merge` function is used but not when the tag is directly assigned.

**Expected behavior**
tfsec should not error since the `repo` tag is getting assigned as outlined in the custom check.

**Desktop (please complete the following information):**
 - OS: Mac OS Calalina

_Edit: Configuration that doesn't work [here](https://github.com/aquasecurity/tfsec/issues/1054#issuecomment-910897604)._
