### ISSUE TITLE
GCP Compute Instance - Validate name by Regex does not work

### ISSUE THREAD

**Issue by Nevana** [aquasecurity/tfsec#1300]
**Describe the bug**
Validating the resource google_compute_instance name by regex doesn´t work.

**To Reproduce**
1. Create a terraform "resource" "google_compute_instance" with name e.g. "dcgvtest01"
```hcl
resource "google_compute_instance" "default" {
  name         = "dcgvtest01"
  machine_type = "e2-medium"
  region       = "europe-west3"
  zone         = "europe-west3-a"
  boot_disk {
    kms_key_self_link = "mykey"
    initialize_params {
      image = "debian-cloud/debian-9"
    }
  }
  network_interface {
    network = "default"
  }

  metadata = {
    #tfsec:ignore:google-compute-no-project-wide-ssh-keys
    block-project-ssh-keys = false
  }
  metadata_startup_script = "echo hi > /test.txt"
  service_account {
    email  = "mysa@mail.com"
    scopes = ["cloud-platform"]
  }
}
```
2. Write a check to validate the name by regex
```yml
- code: CUS003
  description: Custom check to ensure the instances name is correct
  impact: My impact
  resolution: My resolution
  requiredTypes:
  - resource
  requiredLabels:
  - google_compute_instance
  severity: ERROR
  matchSpec:
    name: name
    action: regexMatches
    value: "^dcgv.*$"
```
3. Run tfsec validation with custom check
```bash
$ tfsec .
```
**Expected behavior**
TFSec detects an error ( 1 potential problems detected. )

```
[custom-custom-cus003][HIGH] Custom check failed for resource google_compute_instance.default. 
  /home/myuser/repo/deployment-iac-hello-world/main.tf:16-40


      13 |   version = "0.0.4"
      14 | }
      15 | 
      16 | resource "google_compute_instance" "default" {
      17 |   name         = "dcgvtest01"
      18 |   machine_type = "e2-medium"
      19 |   region       = "europe-west3"
      20 |   zone         = "europe-west3-a"
      21 |   boot_disk {
      22 |     kms_key_self_link = "mykey"
      23 |     initialize_params {
      24 |       image = "debian-cloud/debian-9"
      25 |     }
      26 |   }
      27 |   network_interface {
      28 |     network = "default"
      29 |   }
      30 | 
      31 |   metadata = {
      32 |     #tfsec:ignore:google-compute-no-project-wide-ssh-keys
      33 |     block-project-ssh-keys = false
      34 |   }
      35 |   metadata_startup_script = "echo hi > /test.txt"
      36 |   service_account {
      37 |     email  = "mysa@mail.com"
      38 |     scopes = ["cloud-platform"]
      39 |   }
      40 | }
      41 | 
```
