### ISSUE TITLE
bug: output formatter isn't picking up links for custom checks

### ISSUE THREAD

**Issue by jrobison-sb** [aquasecurity/tfsec#1512]
**Describe the bug**

When a custom rule is triggered, the results don't show the expected link from the `relatedLinks` array in the custom check.

**Expected behavior**
The `relatedLinks` array from the custom check should be present in the `links` array in the result.

**Screenshots/Output**
```
    {
      "description": "Custom check failed for resource module.production_application:aws_sns_topic.insecure_3. SNS Topics require encryption",
      "impact": "SNS data will exist in clear text if it is not encrypted",
      "links": [
        "https://aquasecurity.github.io/tfsec/v1.0.11/checks/custom/custom/SB_001/"
      ],
      "location": {
        "end_line": 11,
        "filename": "/tmp/build/437d4812/pull-request/terraform/modules/aws/application/insecure_infrastructure.tf",
        "start_line": 9
      },
      "long_id": "custom-custom-sb_001",
      "resolution": "Add the kms_master_key_id attribute. Use `kms_master_key_id = \"alias/aws/sns\"` for the default AWS-managed key.",
      "resource": "aws_sns_topic.insecure_3",
      "rule_description": "Require encryption for SNS topics",
      "rule_id": "",
      "rule_provider": "custom",
      "rule_service": "custom",
      "severity": "HIGH",
      "status": 0
    },
```
**System Info**

 - tfsec version: `v1.0.11`
 - terraform version: `v0.14.11`
 - OS: `OSX`

**Example Code**
```
# Custom check
---
checks:
- code: SB_001
  description: Require encryption for SNS topics
  impact: SNS data will exist in clear text if it is not encrypted
  resolution: Add the kms_master_key_id attribute. Use `kms_master_key_id = "alias/aws/sns"` for the default AWS-managed key.
  requiredTypes:
  - resource
  requiredLabels:
  - aws_sns_topic
  severity: ERROR
  matchSpec:
    name: kms_master_key_id
    action: isPresent
  errorMessage: SNS Topics require encryption
  relatedLinks:
  - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sns_topic#kms_master_key_id
```

```
resource "aws_sns_topic" "insecure_3" {
  name = "insecure_3"
}
```
