### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Abansal-ninja** [aquasecurity/tfsec#1526]
**Description**
Found bug with check actions like equals, contains, startwith, regexMatches is not detecting Tag values case sensitivity when creating a custom check to scan for AWS tags. Refer the below example for more info. 

**To Reproduce**
For ex: 
As we know that both AWS Tags keys and values are case sensitive.  In _tfcheck.yaml file if you define to check tag with fruit = apple using any of the above mentioned check action, where in the terraform code you have the tag specified with fruit = Apple. You noticed the case sensitivity between the tag values apple & Apple, then the custom check does not detect anything and passes on. 

1.Add a tag key and value in your terraform code as shown below [fruit = "Apple"]
![image](https://user-images.githubusercontent.com/97044710/153434092-2a4fd2b1-e878-45ad-8099-411c4caacd0f.png)

2. create a custom check with below matchspec. you may use any other actions as well.
![image](https://user-images.githubusercontent.com/97044710/153434264-a42f6ec6-5d59-4ea1-a173-245e0ebf2edd.png)

3. After executing tfsec, we get the below output.
![image](https://user-images.githubusercontent.com/97044710/153434305-720f6622-2887-4df6-9b1e-1e123910f98b.png)

**Expected behavior**
tfsec should detect the case sensitivity of AWS tag values as well with any of the tfsec check actions. 
Please specify if there is any available check action which can detect the tag values case sensitivity.

**System Info**

 - tfsec version: v1.1.4
 - terraform version: v1.1.2
 - OS: windows 10 (19043.1466)

**Additional context**
tfsec check actions are checking the case sensitivity of the Tag keys but not for tag values. for ex:

Case sensitive Tag Keys:
Terraform code tag : fruit = apple   +   tfsec check :  Fruit = apple   -------> this fails as expected and gets detected in output.

Case sensitive Tag Values:
Terraform code tag : fruit = apple   +   tfsec check :  fruit = Apple   -------> this passes and no detection in output.

**Comment by owenrumney** [comment]
Hey @Abansal-ninja  - I'm not sure this is actually correct, and I think that the issue is that you're using `equals` for something that is an interable

I've created an example to validate the bug using the custom check

```yaml
---
checks:
  - code: ensure-fruit-set
    description: Ensure that the fruit is set
    requiredTypes:
      - resource
    requiredLabels:
      - aws_instance
    severity: MEDIUM
    matchSpec:
      name: tags
      action: contains
      value: Fruit
    errorMessage: The required tag is not present
    relatedLinks:
      - http://internal.acmecorp.com/standards/aws/tagging.html
```



```hcl
resource "aws_instance" "example" {

    ami = "something"
    instance_type =  "m2.xlarge"

    root_block_device {
      encrypted = true
    }

    metadata_options {
      http_tokens = "required"
    }

    tags = {
        fruit = "apple"
    }
}
```
When we run tfsec
```bash
tfsec example/1527

Result #1 MEDIUM Custom check failed for resource aws_instance.example. The required tag is not present 
───────────────────────────────────────────────────────────────────────────────────────────────
 main.tf Lines 1-17
───────┬───────────────────────────────────────────────────────────────────────────────────────
    1  │ resource "aws_instance" "example" {
    2  │ 
    3  │     ami = "something"
    4  │     instance_type =  "m2.xlarge"
    5  │ 
    6  │     root_block_device {
    7  │       encrypted = true
    8  │     }
    9  │ 
   10  │     metadata_options {
   11  │       http_tokens = "required"
   12  │     }
   13  │ 
   14  │     tags = {
   15  │         fruit = "apple"
   16  │     }
   17  │ }
───────┴───────────────────────────────────────────────────────────────────────────────────────
          ID custom-custom-ensure-fruit-set

  More Information
  - http://internal.acmecorp.com/standards/aws/tagging.html
───────────────────────────────────────────────────────────────────────────────────────────────


  timings
  ──────────────────────────────────────────
  disk i/o             127.448µs
  hcl parsing          4.577µs
  evaluation           62.924µs
  adaptation           47.575µs
  running checks       1.839114ms
  total                2.248601ms

  counts
  ──────────────────────────────────────────
  blocks               1
  modules              0
  files                1

  results
  ──────────────────────────────────────────
  ignored              0
  excluded             0
  critical             0
  high                 0
  medium               1
  low                  0


  1 potential problem(s) detected.
```

the issue has been found because the tag is `fruit`

when we change the tag to be `Fruit`

```hcl
resource "aws_instance" "example" {

    ami = "something"
    instance_type =  "m2.xlarge"

    root_block_device {
      encrypted = true
    }

    metadata_options {
      http_tokens = "required"
    }

    tags = {
        Fruit = "apple"
    }
}
```

we get the following output

```bash
tfsec example/1527
  timings
  ──────────────────────────────────────────
  disk i/o             150.497µs
  hcl parsing          5.544µs
  evaluation           81.337µs
  adaptation           53.157µs
  running checks       1.945743ms
  total                2.429653ms

  counts
  ──────────────────────────────────────────
  blocks               1
  modules              0
  files                1

  results
  ──────────────────────────────────────────
  ignored              0
  excluded             0
  critical             0
  high                 0
  medium               0
  low                  0


No problems detected!
```

**Comment by owenrumney** [comment]
Just for additional info, and something I need to ensure is documented better

```yaml
---
checks:
  - code: ensure-fruit-set
    description: Ensure that the fruit is set
    requiredTypes:
      - resource
    requiredLabels:
      - aws_instance
    severity: MEDIUM
    matchSpec:
      name: tags
      action: contains
      value: 
        Fruit:
          action: isAny
          value: 
          - banana
          - pear
          - mango
    errorMessage: The required tag is not present
    relatedLinks:
      - http://internal.acmecorp.com/standards/aws/tagging.html`
```

You can specify that you want the value of the tag to be one of a value

```hcl
resource "aws_instance" "example" {

    ami = "something"
    instance_type =  "m2.xlarge"

    root_block_device {
      encrypted = true
    }

    metadata_options {
      http_tokens = "required"
    }

    tags = {
        Fruit = "apple"
    }
}
```

We get an error here 

```bash
tfsec example/1527

Result #1 MEDIUM Custom check failed for resource aws_instance.example. The required tag is not present 
───────────────────────────────────────────────────────────────────────────────────────────────
 main.tf Lines 1-17
───────┬───────────────────────────────────────────────────────────────────────────────────────
    1  │ resource "aws_instance" "example" {
    2  │ 
    3  │     ami = "something"
    4  │     instance_type =  "m2.xlarge"
    5  │ 
    6  │     root_block_device {
    7  │       encrypted = true
    8  │     }
    9  │ 
   10  │     metadata_options {
   11  │       http_tokens = "required"
   12  │     }
   13  │ 
   14  │     tags = {
   15  │         Fruit = "apple"
   16  │     }
   17  │ }
───────┴───────────────────────────────────────────────────────────────────────────────────────
          ID custom-custom-ensure-fruit-set

  More Information
  - http://internal.acmecorp.com/standards/aws/tagging.html
───────────────────────────────────────────────────────────────────────────────────────────────


  timings
  ──────────────────────────────────────────
  disk i/o             132.184µs
  hcl parsing          5.058µs
  evaluation           66.864µs
  adaptation           48.583µs
  running checks       2.027725ms
  total                2.467528ms

  counts
  ──────────────────────────────────────────
  blocks               1
  modules              0
  files                1

  results
  ──────────────────────────────────────────
  ignored              0
  excluded             0
  critical             0
  high                 0
  medium               1
  low                  0


  1 potential problem(s) detected.
```

but if we add `apple` to the options

```yaml
---
checks:
  - code: ensure-fruit-set
    description: Ensure that the fruit is set
    requiredTypes:
      - resource
    requiredLabels:
      - aws_instance
    severity: MEDIUM
    matchSpec:
      name: tags
      action: contains
      value: 
        Fruit:
          action: isAny
          value: 
          - banana
          - pear
          - mango
          - apple
    errorMessage: The required tag is not present
    relatedLinks:
      - http://internal.acmecorp.com/standards/aws/tagging.html
```

now the check will pass because the required match is satisfied

```bash 
tfsec example/1527
  timings
  ──────────────────────────────────────────
  disk i/o             151.008µs
  hcl parsing          6.054µs
  evaluation           86.05µs
  adaptation           56.552µs
  running checks       2.049507ms
  total                2.545992ms

  counts
  ──────────────────────────────────────────
  blocks               1
  modules              0
  files                1

  results
  ──────────────────────────────────────────
  ignored              0
  excluded             0
  critical             0
  high                 0
  medium               0
  low                  0


No problems detected!
```
