### ISSUE TITLE
question: Help with custom check definition

### ISSUE THREAD

**Issue by juan-castrillon** [aquasecurity/tfsec#1580]
Hello! I want to first say thank you for this amazing piece of software! I am a really new user just starting to implement it into our terraform workflow. 

As a noob, I am having some issues understating how to define a simple custom rule:

I want to check that that each `aws_instance` has a tag called "ClusterServer" and that the value of the tag is either "true" or "false". 

In other words, this should pass
```tf
resource "aws_instance" "hashi" {
  ami           = "ami-0d527b8c289b4af7f"
  instance_type = "t3.micro"
  tags = {
    "ClusterServer" = "true"
  }
}
```

My first guess was something like:

```yaml
matchSpec:
    name: tags
    action: isPresent
    subMatch: 
      name: ClusterServer
      action: isAny
      value:
        - "true"
        - "false"
```
This does not pass the tests but strangely enough this does:
```yaml
matchSpec:
    name: tags
    action: isPresent
    subMatch: 
      action: or
      predicateMatchSpec:
        - name: ClusterServer
          action: equals
          value: "true"
        - name: ClusterServer
          action: equals
          value: "false"
```
Could you help me understand why this is the case? Am I missing something in the docs?  I have also tried with `regexMatches` instead of `isAny` without success. It seems to me that only `equals` actions are working

**Comment by owenrumney** [comment]
Hey @juan-castrillon  - glad you like tfsec 

There are a few missing fields - the check should look like this - 

```yaml
---
checks:
- code: TAG_custom
  description: Check the presence of the tag
  errorMessage: Tag isn't there or doesn't match rule
  severity: HIGH
  requiredTypes:
  - resource
  requiredLabels:
  - aws_instance
  matchSpec:
    action: contains
    name: tags
    value:
      ClusterServer:
        action: isAny
        value:
        - true
        - false
```
This is quite a complete contains which is saying tags contains ClusterServer AND the value is any of the provided optional values


Now when we run against your example, we get the custom error

```hcl
resource "aws_instance" "hashi" {
  ami           = "ami-0d527b8c289b4af7f"
  instance_type = "t3.micro"
  tags = {
    "ClusterServer" = "blah"
  }
}
```


```bash
Result #1 HIGH Custom check failed for resource aws_instance.hashi. Tag isn't there or doesn't match rule 
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 main.tf Lines 1-7
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    1  │ resource "aws_instance" "hashi" {
    2  │   ami           = "ami-0d527b8c289b4af7f"
    3  │   instance_type = "t3.micro"
    4  │   tags = {
    5  │     "ClusterServer" = "blah"
    6  │   }
    7  │ }
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
          ID custom-custom-tag_custom

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

When we correct the Terraform to provide the correct value


```hcl
resource "aws_instance" "hashi" {
  ami           = "ami-0d527b8c289b4af7f"
  instance_type = "t3.micro"
  tags = {
    "ClusterServer" = true
  }
}
```

it doesn't create the error.

Hope that helps!

**Comment by juan-castrillon** [comment]
@owenrumney Thanks a lot for the help and the resources!

I see what my issue was now, I didn't know this syntax was possible:

```
value:
      ClusterServer:
        action: isAny
        value:
        - true
        - false
```

That seems to do the trick and is quite verbose, in a good way.  As a tiny comment, I didn't really found anything in the docs, that lead me to believe that was supported, so that might be something you could add in a future update. 

Thanks again!
