### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by jmflynn81** [aquasecurity/tfsec#1592]
**TFSec fails on defsec imports**

When using TFSec in github workflow, receive the following error...

```
github.com/aquasecurity/tfsec/cmd/tfsec imports
	github.com/aquasecurity/tfsec/internal/app/tfsec/cmd imports
	github.com/aquasecurity/tfsec/internal/pkg/rules imports
	github.com/aquasecurity/tfsec/internal/pkg/rules/general/secrets imports
	github.com/aquasecurity/defsec/rules/general/secrets: cannot find module providing package github.com/aquasecurity/defsec/rules/general/secrets
/entrypoint.sh: line 18: /go/bin/tfsec: No such file or directory
```
This seems to be since version 0.17.2 of aquasecurity/defsec was released 

**To Reproduce**

Using the following github workflow action...

```
  tfsec:
    name: TFSec Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Terraform security scan
        uses: triat/terraform-security-scan@v3.0.1
        with:
          tfsec_actions_comment: false
          tfsec_actions_working_dir: terraform/environment/dev
```

**Expected behaviour**
TFSec to run normally and produce relevant outputs
