### ISSUE TITLE
bug: `tfsec-checkgen` success for an invalid config

### ISSUE THREAD

**Issue by swapzero** [aquasecurity/tfsec#1607]
**Describe the bug**

tfsec-checkgen returns `Config is valid` for an invalid config.
Subsequently `tfsec` returns:
```
0 potential problem(s) detected.
```
for this invalid config.

**To Reproduce**
- do not follow the schema (break `checks` list):
```diff
checks:
-- code: CUS001
+  code: CUS001
```
```
# I used an example from your documentation
cat > test.yaml <<-EOF
---
checks:
  code: CUS001
  description: Custom check to ensure the CostCentre tag is applied to EC2 instances
  impact: By not having CostCentre we can't keep track of billing
  resolution: Add the CostCentre tag
  requiredTypes:
  - resource
  requiredLabels:
  - aws_instance
  severity: ERROR
  matchSpec:
    name: tags
    action: contains
    value: CostCentre
  errorMessage: The required CostCentre tag was missing
  relatedLinks:
  - http://internal.acmecorp.com/standards/aws/tagging.html
EOF
```
- run `tfsec-checkgen`
```
$ ./tfsec-checkgen validate test.yaml
Config is valid
$
$ head -3 test.yaml
---
checks:
  code: CUS001
```

❗ What is most concerning here is that such invalid configuration "tricks" `tfsec` into reporting no problems **at all**.
I used an existing list of custom checks defined in a `.yml` file to test:
- with a broken configuration
```
$  ./tfsec --concise-output  --filter-results custom-custom-checkname1here,custom-custom-checkname2here
  0 potential problem(s) detected.
```
- with a proper configuration
```
./tfsec --concise-output  --filter-results custom-custom-checkname1here,custom-custom-checkname2here
 47 passed, 3 potential problem(s) detected.
```
**Expected behavior**

The validator should check the structure against the schema and error out.

**Screenshots/Output**

**System Info**

 - tfsec version: `1.10.0`
 - terraform version: `-`
 - OS: `OSX`

**Example Code**

**Additional context**
