### ISSUE TITLE
bug: latest release missing downloads

### ISSUE THREAD

**Issue by vf-ford** [aquasecurity/tfsec#1618]
**Describe the bug**

When a new release is issued, there is a period of time when the downloads are not available, breaking automated downloads of tfsec in pipelines

**To Reproduce**
1. Wait for new release of tfsec
2. run the following commands
   ```bash
   curl --location "https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64" \
        --output "/usr/bin/tfsec"`
   chmod u+x /usr/bin/tfsec
   echo "Running tfsec version $(tfsec --version)"
   ```
3. See error message

**Expected behavior**

The latest release of tfsec should be downloaded

**Screenshots/Output**

See screenshot where latest release has only the source code as assets
![image](https://user-images.githubusercontent.com/52499138/159694554-310c3fb7-e06f-410e-8117-fb1cf21374ef.png)

**Additional context**

If there is a more error-proof method of fetching the latest tfsec release, please let us know

**Comment by hakuno** [comment]
+1

**Comment by mjung** [comment]
Note: workaround is to pin the tfsec version to prior release, e.g. 

```
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@main
        with:
          tfsec_version: v1.13.0
```
