### ISSUE TITLE
question: check backend.tf file && opa policies from bundles

### ISSUE THREAD

**Issue by jSebastianAR** [aquasecurity/tfsec#1688]
Hi, i am a very new user of tfsec, I have been reading your docs and so on, because I need to use opa to customize some policies.

But I couldn't find something with opa to check the backend.tf file where I define where the state is gonna be saved, so I found what you call "Custom Checks" https://aquasecurity.github.io/tfsec/v1.18.0/guides/configuration/custom-checks/

But even with that I don't have it clear yet, because the custom checks specify that is possible to define what type you want to check (requiredTypes) and this types are "resource, data, module, variable" and I don't know where my config fits on one of these options because my backend.tf file looks like this:

```
terraform {
  backend "s3" {
    bucket               = "bucket-name"
    workspace_key_prefix = "project"
    key                  = "path/to/tfstate/project.tfstate"
    region               = "region"
    acl                  = "bucket-owner-full-control"
    encrypt              = true
  }

  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
    postgresql = {
      source = "cyrilgdn/postgresql"
    }
    random = {
      source = "hashicorp/random"
    }
  }

  required_version = "~> 1.0.0"
}
```

I've been trying with this custom check config:

```
checks:
- code: CUS001
  description: Custom check to ensure the S3 backend has the correct configuration
  impact: By not having key prefix we won't have the correct configuration for tf.states
  resolution: Add the s3 workspace_key_prefix, key fields and acl must be equal to "bucket-owner-full-control"
  requiredTypes:
  - resource
  requiredLabels:
  - backend
  severity: CRITICAL
  matchSpec:
    action: isPresent
    name: workspace_key_prefix
    subMatch : 
      action : and
      predicateMatchSpec:
        - action : isPresent
          name : key
        - action : equals
          name: acl
          value : bucket-owner-full-control
```
When I try tfsec with this configuration there's no difference that if I don't specify custom checks

The command line that I use is:

$ tfsec /path/to/terraform/files

When I want to use opa policies is:

$ tfsec /path/to/terraform/files --rego-policy-dir /path/to/rego/policies

and my directory where I saved the custom checks and config for tfsec is the same where I execute the above commands in the ".tfsec" folder and its content is like we can see in the image:

![image](https://user-images.githubusercontent.com/38919117/164109320-0f57bee3-3464-48b3-a439-e50dc999e56f.png)

1. is there a way to specify a block like the defined on my .tf file inside the custom checks?
2. or is it possible from a custom policy with opa?
3. also I would like to know if is there a way to download bundles of policies (many rego files) from a server and use them to check terraform config, this because the idea is to have these rego policies in a centralized server.

I'll really appreciate your answer, and thanks in advance for your awesome tool.

**Comment by owenrumney** [comment]
Hey @jSebastianAR  - custom checks might not be able to support this but I'll have a little go now.

In other news, we support Rego if you want to use that https://aquasecurity.github.io/tfsec/v1.22.1/guides/rego/rego/

**Comment by owenrumney** [comment]
You were pretty much there with your custom check - this works

```yaml
checks:
- code: CUS001
  description: Custom check to ensure the S3 backend has the correct configuration
  impact: By not having key prefix we won't have the correct configuration for tf.states
  resolution: Add the s3 workspace_key_prefix, key fields and acl must be equal to "bucket-owner-full-control"
  requiredTypes:
  - terraform
  requiredLabels:
  - "*"
  severity: CRITICAL
  matchSpec:
    action: isPresent
    name: backend
    subMatch : 
      action : and
      predicateMatchSpec:
        - action: isPresent
          name: workspace_key_prefix
        - action : isPresent
          name : key
        - action : equals
          name: acl
          value : bucket-owner-full-control
```

Apologies for the delay in responding - hope this is still useful
