### ISSUE TITLE
bug: Checks on lifecycl ignore_changes requires strings

### ISSUE THREAD

**Issue by mijdavis2** [aquasecurity/tfsec#1689]
**Describe the bug**
To use tfsec to check `ignore_changes` in `lifecycle`, strings are required in the terraform config. Ref: https://github.com/aquasecurity/tfsec/discussions/1675

**To Reproduce**
1. Create a custom check for `ignore_changes`:
	```yaml
	checks:
	    - code: okta-app-must-ignore-groups-users
	      description: Ensure groups and users are ignored on okta apps.
	      impact: Maintaining groups and users in okta_app is deprecated.
	      resolution: Ignore groups and instead use okta_app_group_assignments
	      requiredTypes:
	        - resource
	      requiredLabels:
	        - "okta_app"
	      severity: CRITICAL
	      matchSpec:
	        name: lifecycle
	        action: isPresent
	        subMatch:
	          action: and
	          predicateMatchSpec:
	            - name: ignore_changes
	              action: contains
	              value: users
	            - name: ignore_changes
	              action: contains
	              value: groups
	      errorMessage: Groups/users not ignored in okta app
	```
2. Create main.tf with said resources using standard syntax (no strings):
	```hcl
	resource "okta_app_saml" "this" {
	    [...]
	    
	    lifecycle {
	      ignore_changes = [
	        users, groups,
	      ]
	    }
	}
	```
3. Run tfsec. 
4. See failure.

**Expected behavior**

The above should not result in a failure. 

**Workaround**

Use strings like so:
```hcl
resource "okta_app_saml" "this" {
	[...]
	    
	lifecycle {
	      ignore_changes = [
	          "users", "groups",
	      ]
	}
}
```

**System Info**

 - tfsec version: `0.63.1`
 - terraform version: `1.0.3`
 - OS: `linux`
