### ISSUE TITLE
bug: SARIF URI scheme "https" did not match the checkout URI scheme "file"

### ISSUE THREAD

**Issue by frank-bee** [aquasecurity/tfsec#1811]
**Describe the bug**
I get an error when uploading the produces sarif file to github

```
 Error: Code Scanning could not process the submitted SARIF file:
  SARIF URI scheme "https" did not match the checkout URI scheme "file",
```
the produced sarif file has such entries

```
  {
          "ruleId": "aws-vpc-no-public-egress-sgr",
          "ruleIndex": 20,
          "level": "error",
          "message": {
            "text": "Security group rule allows egress to multiple public internet addresses."
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "https://github.com/bosch-top98-ai-know/terraform-aws-small-modules.git/modules/opensearch?ref=v0.0.72/github/workspace/dev/.terraform/modules/opensearch-services-team/modules/opensearch/security_group.tf"
                },
                "region": {
                  "startLine": 30,
                  "endLine": 30
                }
              }
            }
          ]
        },
```

**To Reproduce**
Run this in a github pipeline (with a terraform plan in advance incl. private terraform modules)
```
     - name: tfsec
        uses: aquasecurity/tfsec-sarif-action@v0.1.3
        with:
          sarif_file: tfsec.sarif
          working_directory: dev

      - name: showsarif
        run: |
          sed -i 's/git:://g' tfsec.sarif
          sed -i 's+https:/github+https://github+g' tfsec.sarif
          cat ./tfsec.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif

```
