### ISSUE TITLE
question: Custom check for required_version in terraform block

### ISSUE THREAD

**Issue by nantiferov** [aquasecurity/tfsec#1850]
Hi,

I'm wondering how works terraform block parsing in tfsec. It seems to me that in terraform all blocks defined in different places are merged, so it's possible to define **required_version** once in a module and then skip it in every state. But it seems not the case in tfsec.

I'm trying to add custom check like this to enforce `required_version` defined. But it will force me to define it everywhere (in each **terraform** block afaik).

Am I right and there is no way atm to make it more flexible?

## Code examples

Check:

```yaml
---
checks:
  - code: CUS001
    description: Terraform version constraint is not set
    impact: By not having required_version set in terraform block
    resolution: Set required_version for state
    requiredTypes:
      - terraform
    requiredLabels:
      - "*"
    severity: CRITICAL
    matchSpec:
      action: isPresent
      name: required_version
```

Module snippet:

```terraform
terraform {
  required_version = "~> 1.2.0"
}
```

State looks like

```terraform
module "test" {
  source = "../module"
}

terraform {
  backend "s3" {
....
  }
}
```

## Tfsec output

Too long, but basically it prints that required_version is missing in every block found in state.

```log
Result #20 CRITICAL Custom check failed for resource terraform.  
───────��────────────────────────────────────────────────────────────────────────
 terraform.tf Lines 1-3
───────┬────────────────────────────────────────────────────────────────────────
    1  │ terraform {
    2  │   backend "s3" {}
    3  │ }
───────┴────────────────────────────────────────────────────────────────────────
          ID custom-custom-cus001
      Impact By not having required_version set in terraform block
  Resolution Set required_version for state

────────────────────────────────────────────────────────────────────────────────
```

P.S. Check based on this answer https://github.com/aquasecurity/tfsec/issues/1688#issuecomment-1149729281
It seems `requiredTypes = terraform` is **missing** in documentation https://aquasecurity.github.io/tfsec/v1.27.1/guides/configuration/custom-checks/
