### ISSUE TITLE
question: how to use the requiresPresence check correctly

### ISSUE THREAD

**Issue by nicobbg** [aquasecurity/tfsec#1886]
n00b question, I don't understand how to use the requiresPresence check, can someone explains it to me?

I want to check my code contains a _myprivatecloud_vpc_flow_log_ resource.

I have a rule like this:
```yaml
requiredTypes:
- resource
requiredLabels:
- <here I don't know what to put>
matchSpec:
  name: myprivatecloud_vpc_flow_log
  action: requiresPresence
```
If I set requiredLabels to _myprivatecloud_vpc_flow_log_ it does not trigger (my test code does not contains the resource).
_requiredLabels_ is mandatory, I cannot set it to anything else because the searched resource is not nested in another one.

I am probably missing something.
