### ISSUE TITLE
question: Custom check definition help

### ISSUE THREAD

**Issue by mobershall** [aquasecurity/tfsec#1909]
Similar to [issue #1000](https://github.com/aquasecurity/tfsec/issues/1000) I am trying to write a custom check for security group and security group rule resources who have an open cidr `0.0.0.0/0` on either port 22 or 3389.

I tried modifying the example given in the issue conversation, but it doesn't seem to work for my test cases.

sg rule custom check:
```
requiredTypes: [resource]
requiredLabels: [aws_security_group_rule]
matchSpec:
  action: or
  predicateMatchSpec:
  - name: type
    action: notEqual
    value: ingress
  - action: or
    predicateMatchSpec:
    - name: cidr_blocks
      action: notContains
      value: 0.0.0.0/0
    - name: from_port
      action: isNone
      value: [22, 3389]
```

sg custom check:
```
matchSpec:
name: ingress
action: notPresent
subMatch:
  action: or
  predicateMatchSpec:
  - name: cidr_blocks
    action: notContains
    value: 0.0.0.0/0
  - name: from_port
    action: isNone
    value: [22, 3389]`
```

test cases that should be marked:
```
resource "aws_security_group_rule" "rule22" {
  type              = "ingress"
  description       = "should be marked"
  from_port         = 22
  to_port           = 22
  protocol          = "tcp"
  cidr_blocks       = ["0.0.0.0/0"]
  security_group_id = "sg-03eee855906d90157"
}
resource "aws_security_group" "sg22" {
  name        = "allow_all"
  description = "Allow all inbound traffic on ports 22 and 3389"
  vpc_id      = aws_vpc.main.id
  ingress {
    description      = "open to internet"
    from_port        = 22
    to_port          = 22
    protocol         = "tcp"
    cidr_blocks      = ["0.0.0.0/0"]
  }
}
resource "aws_security_group_rule" "rule3389" {
  type              = "ingress"
  description       = "open to internet"
  from_port         = 3389
  to_port           = 3389
  protocol          = "tcp"
  cidr_blocks       = ["0.0.0.0/0"]
  security_group_id = "sg-03eee855906d90157"
}
resource "aws_security_group" "sg3389" {
  name        = "allow_all"
  description = "Allow all inbound traffic on ports 22 and 3389"
  vpc_id      = aws_vpc.main.id
  ingress {
    description      = "open to internet"
    from_port        = 3389
    to_port          = 3389
    protocol         = "tcp"
    cidr_blocks      = ["0.0.0.0/0"]
  }
}
```

test cases that should not be marked:
```
resource "aws_security_group_rule" "pass_specific" {
  type              = "ingress"
  description       = "this should not be marked"
  from_port         = 3872
  to_port           = 3872
  protocol          = "tcp"
  cidr_blocks       = [<list of values redacted>]
  security_group_id = "sg-1234567890"
}
resource "aws_security_group" "pass_specific_sg" {
  name        = "testsg_pass"
  description = "this should not be marked"
  vpc_id      = aws_vpc.main.id
  ingress {
    description      = "Ingress from UPN Oracle"
    from_port        = 3872
    to_port          = 3872
    protocol         = "tcp"
    cidr_blocks      = [<list of values redacted>]
  }
}

resource "aws_security_group_rule" "pass_all" {
  type              = "egress"
  description       = "egress type should pass"
  from_port         = 3390
  to_port           = 3390
  protocol          = "tcp"
  cidr_blocks       = ["10.0.0.1/0"]
  security_group_id = "sg-1234567890"
}
resource "aws_security_group" "pass_all" {
  name        = "testsg_pass_egress"
  description = "egress should pass"
  vpc_id      = aws_vpc.main.id
  egress {
    description      = "egress should pass"
    from_port        = 3390
    to_port          = 3390
    protocol         = "tcp"
    cidr_blocks      = ["10.0.0.1/0"]
  }
}

resource "aws_security_group_rule" "pass_egress" {
  type              = "egress"
  description       = "egress type should pass"
  from_port         = 3389
  to_port           = 3389
  protocol          = "tcp"
  cidr_blocks       = ["0.0.0.0/0"]
  security_group_id = "sg-1234567890"
}
resource "aws_security_group" "pass_egress" {
  name        = "testsg_pass_egress"
  description = "egress should pass"
  vpc_id      = aws_vpc.main.id
  egress {
    description      = "egress should pass"
    from_port        = 3389
    to_port          = 3389
    protocol         = "tcp"
    cidr_blocks      = ["0.0.0.0/0"]
  }
}

resource "aws_security_group_rule" "pass_port" {
  type              = "ingress"
  description       = "ports other than 3389 and 22 should pass"
  from_port         = 3390
  to_port           = 3390
  protocol          = "tcp"
  cidr_blocks       = ["0.0.0.0/0"]
  security_group_id = "sg-1234567890"
}
resource "aws_security_group" "pass_port" {
  name        = "testsg_pass_port"
  description = "ports other than 3389 and 22 should pass"
  vpc_id      = aws_vpc.main.id
  ingress {
    description      = "ports other than 3389 and 22 should pass"
    from_port        = 23
    to_port          = 23
    protocol         = "tcp"
    cidr_blocks      = ["0.0.0.0/0"]
  }
}

resource "aws_security_group_rule" "pass_cidr" {
  type              = "ingress"
  description       = "cidr blocks without 0s regardless of port should pass"
  from_port         = 22
  to_port           = 22
  protocol          = "tcp"
  cidr_blocks       = ["10.0.0.1/0"]
  security_group_id = "sg-1234567890"
}
resource "aws_security_group" "pass_cidr" {
  name        = "testsg_pass_cidr"
  description = "ports other than 3389 and 22 should pass"
  vpc_id      = aws_vpc.main.id
  ingress {
    description      = "ports other than 3389 and 22 should pass"
    from_port        = 22
    to_port          = 22
    protocol         = "tcp"
    cidr_blocks      = ["10.0.0.1/0"]
  }
}
```

---

to add and potentially raise a bug,

a simple check to match any security group with an ingress rule
```
requiredTypes: [resource]
requiredLabels: [aws_security_group]
matchSpec:
  name: ingress
  action: notPresent
```
marks the following tf config as expected:
```
resource "aws_security_group" "pass_cidr" {
  name        = "testsg_pass_cidr"
  description = "ports other than 3389 and 22 should pass"
  vpc_id      = aws_vpc.main.id
  ingress {
    description      = "ports other than 3389 and 22 should pass"
    from_port        = 22
    to_port          = 22
    protocol         = "tcp"
    cidr_blocks      = ["10.0.0.1/0"]
  }
}
```
adding to custom tfsec rule to match security groups with ‘0.0.0.0/0’ in the cidr_blocks list value
```
requiredTypes: [resource]
requiredLabels: [aws_security_group]
matchSpec:
  name: ingress
  action: notPresent
  subMatch:
    name: cidr_blocks
    action: notContains
    value: 0.0.0.0/0
```
unexpectedly matches the above config as well
