### ISSUE TITLE
question: tfsec custom check on the required providers

### ISSUE THREAD

**Issue by heriberto-mb** [aquasecurity/tfsec#2003]
We have experienced some issues when our developers leave the > in the azurerm version under required_providers.
We would like to check that our developers pin the versions in their code using equals:

```
terraform {
  backend "azurerm" {}
  required_providers {
    azurerm = {
      **version = ">=3.0"**
      source  = "hashicorp/azurerm"
    }
    azuread = {
      version = ">=0.7.0"
      source  = "hashicorp/azuread"
    }
  }
}
```

We want tfsec to report the greater than value (>=3.0), the correct option would be "3.0" or "=3.0".

I've tried the following code but it doesn't pick it up. Can you tell me what is wrong pls?

```
---
checks:
- code: check_required_providers
  description: Ensure that teams are pinning their resource versions/provider in their code.
  impact: Possible version collisions when not pinning the Azure provider.
  resolution: Use the equals operator in the provider version.
  requiredTypes:
  - required_providers
  requiredLabels:
  - azurerm
  severity: HIGH
  matchSpec:
    name: version
    action: isAny
    value:
    - "<"
    - ">"
  errorMessage: The version should not contain > or < in the version under required_providers, it can only use equals.
  relatedLinks:  - https://github.com/our_web_page
```
