### ISSUE TITLE
question: How to check my provider.tf file

### ISSUE THREAD

**Issue by heriberto-mb** [aquasecurity/tfsec#2007]
I have the following definition in my **provider.tf** file:

```
provider "azuread" {}

terraform {
  backend "azurerm" {}
  required_providers {
    azurerm = {
      version = ">=3.0"
      source  = "hashicorp/azurerm"
    }
    azuread = {
      version = ">=0.7.0"
      source  = "hashicorp/azuread"
    }
  }
}
# Adding subscription aliases for azure resource manager and key vault features
provider "azurerm" {
  alias = "prod_sub"
  features {}
  subscription_id = "d083478e-37a0-4e9d-b8f0-c4d6d3225ac2"
}
provider "azurerm" {
  alias = "devl_sub"
  features {}
  subscription_id = "31deaf44-bdac-40c1-89fa-376f984921c0"
}
provider "azurerm" {
  features {
    key_vault {
      // When Key Vaults or their contents are destroyed just delete, don't purge
      purge_soft_delete_on_destroy = false
      purge_soft_deleted_certificates_on_destroy = false
      purge_soft_deleted_keys_on_destroy = false
      purge_soft_deleted_secrets_on_destroy = false
    }
  }
}
```
I want to make sure that the provider is correctly pinned, and we want to check that there are no ">"s in the version **on the line number 7.**
In my case I would like the developer to substitute ">=3.0" to "=3.0".

Here's the **tfsec check** that I tried to implement, however it is not picking it up:
```
---
checks:
- code: check_required_providers
  description: Ensure that teams are pinning their resource versions/provider in their code.
  impact: Possible version collisions when not pinning the Azure provider.
  resolution: Use the equals operator in the provider version.
  requiredTypes:
  - terraform
  requiredLabels:
  - required_providers
  severity: HIGH
  matchSpec:
    name: version
    action: notContains
    value: ">"
  errorMessage: The version should not contain > or < in the required_providers, it can only use equals.
  relatedLinks:
  - https://github.com/Jackson-National/terraform-modules-vm-managed-disks
```
@owenrumney and @itaysk Could I pick up your brain really quick on this one? I've tried different variations of the check, but none of them work.
custom-check
