### ISSUE TITLE
bug: --custom_check_rurl doesn't seem to work fine with a github page

### ISSUE THREAD

**Issue by heriberto-mb** [aquasecurity/tfsec#2012]
**Describe the bug**
--custom_check_url doesn't seem to work fine with a github page, it doesn't pick up the checks, but it works fine if I use a local file.
I was expecting it to pickup all the rules defined in the URL specified to the parameter.

**To Reproduce**
1.  Create a tfsec check rule in github, for example:
https://github.com/Jackson-National/tfsec-custom-rules/blob/main/.tfsec/tfsec_check_modules.yml

contents of tfsec_check_modules.yml:
```
---
checks:
- code: check_modules
  description: Custom check to ensure that we use the custom modules at Jackson.
  impact: Use the modules that the Azure Engineering team already created.
  resolution: Use the modules available at https://github.com/orgs/Jackson-National/teams/terraform-modules/repositories
  requiredTypes:
  - resource
  requiredLabels:
  - azurerm_managed_disk
  severity: HIGH
  matchSpec:
    action: inModule        
  errorMessage: azurerm_managed_disk should be created by a module
  relatedLinks:
  - https://github.com/Jackson-National/terraform-modules-vm-managed-disks
```

Here's the example of the code we wanted to validate, it should have identified it as an exception to the check. (It works fine if we define the check locally).
```
#Example to validate the tfsec check rule #1
resource "azurerm_managed_disk" "example" {
  name                 = "acctestmd"
  location             = var.location
  resource_group_name  = azurerm_resource_group.rg.name
  storage_account_type = "Standard_LRS"
  create_option        = "Empty"
  disk_size_gb         = "1"

  tags = {
    environment = "staging"
  }
}
```

2. When we run the following command, the tfsec check doesn't pick it up:
tfsec terraform --exclude-downloaded-modules --custom-check-url https://github.com/Jackson-National/tfsec-custom-rules/tree/main/.tfsec

**Expected behavior**
I would have expected it to apply all the checks that exist in the URL and alert us. However, it doesn't generate any alert even if we put the whole file name in the URL. (It alerts us correctly if we use a local file).

**Output of your tfsec command with --debug flag**
```
$ tfsec terraform --exclude-downloaded-modules --custom-check-url https://github.com/Jackson-National/tfsec-custom-rules/tree/main/.tfsec

  timings
  ──────────────────────────────────────────
  disk i/o             22.7225ms
  parsing              15.5583717s
  adaptation           0s
  checks               17.2043ms
  total                15.5982985s

  counts
  ──────────────────────────────────────────
  modules downloaded   0
  modules processed    12
  blocks processed     438
  files read           47

  results
  ──────────────────────────────────────────
  passed               2
  ignored              13
  critical             0
  high                 0
  medium               0
  low                  0


No problems detected!
```

**System Info**
 - tfsec version: `v1.28.1`
 - terraform version: `3.0`
 - OS: `ubuntu`

**Example Code**
Here's the example of the code we wanted to validate, it should have identified it as an exception to the check. (It works fine if we define the check locally).
```
#Example to validate the tfsec check rule #1
resource "azurerm_managed_disk" "example" {
  name                 = "acctestmd"
  location             = var.location
  resource_group_name  = azurerm_resource_group.rg.name
  storage_account_type = "Standard_LRS"
  create_option        = "Empty"
  disk_size_gb         = "1"

  tags = {
    environment = "staging"
  }
}
```

**Additional context**
