### ISSUE TITLE
bug:  contains and startsWith doesn't work properly when doing submatches

### ISSUE THREAD

**Issue by heriberto-mb** [aquasecurity/tfsec#2022]
**Describe the bug**
contains and startsWith doesn't work properly when doing submatches

**To Reproduce**
Having this code:
```
terraform {
  backend "azurerm" {}  
  required_providers {
    azurerm = {
      version = "0>=3.0"
      source  = "hashicorp/azurerm"
    }
    azuread = {
      version = "0>=0.7.0"
      source  = "hashicorp/azuread"
    }
  }
}
```
If you try to run the following tfsec check and switch between these options: **contains/startsWith/endsWith** on line 20, you will find that the only option that works as expected is endWith:
```
---
checks:
- code: check_provider_is_pinned
  description: Ensure that teams are pinning their resource versions/provider in their code.
  impact: Possible version collisions when not pinning the Azure provider.
  resolution: Use the equals operator in the provider version.
  requiredTypes:
  - terraform
  requiredLabels:
  - "*"
  severity: HIGH
  matchSpec:
    action: isPresent
    name: required_providers
    subMatch:
      action: isPresent
      name: azurerm
      subMatch:
        name: version
        action: endsWith
        value: 0
  errorMessage: Version should not contain > It should only contain equals (=)
  relatedLinks:
  - https://registry.terraform.io/providers/hashicorp/aws/latest/docs#default_tags
```

**Expected behavior**
I would have expected that **contains** and **startsWith** would not raise any alerts, but it does.

**Output of your tfsec command with --debug flag**
I collected the file, but it is quite big, if you want I can share it via email. Or post it in a separate comment below.

**System Info**

 - tfsec version: v1.28.1
 - terraform version: 1.3.8
 - OS: ubuntu

**Example Code**
```
terraform {
  backend "azurerm" {}  
  required_providers {
    azurerm = {
      version = "0>=3.0"
      source  = "hashicorp/azurerm"
    }
    azuread = {
      version = "0>=0.7.0"
      source  = "hashicorp/azuread"
    }
  }
}
```

**Additional context**
