### ISSUE TITLE
bug: something doesn't seem to be right when validating azurerm_role_assignment

### ISSUE THREAD

**Issue by heriberto-mb** [aquasecurity/tfsec#2030]
**Describe the bug**
something doesn't seem to be right when validating **azurerm_role_assignment**

**To Reproduce**
1. Having the following code:
```
 resource "azurerm_role_assignment" "assign_kv0" {
  for_each = {
    for group in data.azuread_group.ad_groups : group.display_name => group
  }
  scope                = module.liabmodel_key_vault.key_vault.id
  role_definition_name = var.keyvault0_RBAC_name
  principal_id         = each.value["id"]
}
```
2. Create the following rule:
```
---
checks: 
- code: role_assignment
  description: Custom check to ensure that there are no role assignments.
  impact: Assigning administrative roles could represent a high security risk.
  resolution: Avoid granting role assignments to specific groups.
  requiredTypes:
  - resource
  requiredLabels:
  - azurerm_role_assignment
  severity: HIGH
  matchSpec:
    name: role_definition_name
    action: notPresent    
  errorMessage: role_definition_name cannot be given when using azurerm_role_assignment per Jackson's policies.
  relatedLinks:
  - https://github.com/
```

The rule doesn't seem to work with that specific type of resource, however, it works if we use another resource, i.e. azurerm_managed_disk.

**Expected behavior**
I would have expected the custome check to alert us because role_definition_name was present.

**Output of your tfsec command with --debug flag**
tfsec doesn't detect the custom rule

**System Info**

 - tfsec version: `1.28.1`
 - terraform version: `1.3.8`
 - OS: `Windows`

**Example Code**
Already specified above.

**Additional context**
