### ISSUE TITLE
contains in custom checks to have more power

### ISSUE THREAD

**Issue by robertstettner** [aquasecurity/tfsec#784]
Similar to #774 , but I would like to have control over the operation in question. In my case I would like `isAny`, but I can see `regexMatches` being powerful here too.

```yaml
---
checks:
  - code: TAG_custom
    description: Custom check to ensure the Environment tag is applied
    errorMessage: The required Environment tag was missing or invalid
    matchSpec:
      action: contains
      name: tags
      value: 
        Environment:
          action: isAny
          value:
          - dev
          - test
          - staging
          - production
    requiredTypes:
    - resource
    severity: ERROR
    requiredLabels:
    - aws_lb
```

**Comment by grantkl** [comment]
I probably should have been more clear in #774 as this is what I was looking for as well (though even a single match used to fail).

**Comment by owenrumney** [comment]
Hey @robertstettner  - this is done, pretty much exactly as requested in #847 - checkout the example in the PR

**Comment by grantkl** [comment]
@owenrumney I tested this out today and couldn't get it to work. I hacked together a quick test that shows it not matching when it should.

```
package custom

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func init() {
	givenCheck(`{
  "checks": [
    {
      "code": "CUSTOM_AWSTAG",
      "description": "AWS Environment tag is required",
      "requiredTypes": [
        "resource"
      ],
      "requiredLabels": [
        "aws_instance"
      ],
      "severity": "ERROR",
      "matchSpec": {
        "action": "contains",  
        "name": "tags",
        "value": {
          "Environment": {
            "action": "isAny",
            "value": [
              "production",
	      "dev"
	    ]
          }
        }
      }
    }
  ]
}`)
}

func TestAWSTagSubMatchFailure(t *testing.T) {
	scanResults := scanTerraform(t, `
resource "aws_instance" "bastion" {
  metadata_options {
    http_endpoint               = "enabled"
    http_put_response_hop_limit = 1
    http_tokens                 = "required"
  }

  tags = {
    Environment = "test"
  }
}
`)
	assert.Len(t, scanResults, 1)
}

func TestAWSTagSubMatchSuccess(t *testing.T) {
	scanResults := scanTerraform(t, `
resource "aws_instance" "bastion" {
  metadata_options {
    http_endpoint               = "enabled"
    http_put_response_hop_limit = 1
    http_tokens                 = "required"
  }

  tags = {
    Environment = "production"
  }
}
`)
	assert.Len(t, scanResults, 0)
}
```

**Comment by grantkl** [comment]
@owenrumney I'm not sure if that will fix my problem or not, for my manual tests I was using yaml but it still wasn't working. I just didn't see a quick helper method for creating a yaml check in the unit tests so I used json. 

Here's what my yaml looked like:
```
---
checks:
  - code: TAG_Environment
    description: Custom check to ensure the Environment tag is applied
    errorMessage: The required Environment tag was missing
    matchSpec:
      action: contains
      name: tags
      value:
        Environment:
          action: isAny
          value:
            - production
            - development
    requiredTypes:
    - resource
    severity: ERROR
    requiredLabels:
    - aws_instance
 ```
